// src/vue-project/src/components/Message.vue
<script setup lang="ts">

import { ref } from "vue";

export interface MessageData {
    sender: User,
    date: Date,
    content: string;
}

export interface User {
    username: string,
    avatar? : string
}

interface Props {
    continuation?: boolean,
    message: MessageData
}

const props = withDefaults(defineProps<Props>(), {
    continuation: false
})

let isHovered = ref(false);

function handleOver() {
    isHovered.value = true
}

function handleLeave() {
    isHovered.value = false
}

</script>

<template>
    <v-row :class="props.continuation ? 'mt-0' : 'mt-1'" class="hover:bg-gray-200" no-gutters align="start" @mouseover="handleOver" @mouseleave="handleLeave">
        <div class="ml-3 mr-1 mt-1">
            <v-avatar v-show="!props.continuation" class="hover:cursor-pointer">
                <v-img
                        v-if="message.sender.avatar"
                        alt="Avatar"
                        :src="message.sender.avatar"
                />
                <span
                        v-else
                        class="rounded bg-blue-accent-3 pa-4 font-weight-bold">
                    {{message.sender.username.slice(0, 2)}}
                </span>
            </v-avatar>

            <div class="mr-10" v-show="props.continuation && !isHovered"></div>
            <div class="text-sm-caption font-weight-thin ml-[9px]" v-show="props.continuation && isHovered">
                {{ message.date.toLocaleTimeString().slice(0, -3) }}
            </div>
        </div>

        <div class="ml-3">
            <div v-show="!props.continuation">
                <p class="font-weight-medium">{{message.sender.username}} <span v-show="!props.continuation"
                                                           class="text-sm-caption font-weight-thin">{{
                        message.date.toLocaleString().slice(0, -3)
                    }}</span></p>
            </div>
            <div>
                <p class="-mt-0.5 mb-0.5">{{message.content}}</p>
            </div>
        </div>
    </v-row>
</template>

<style scoped>

</style>

// src/my-app/src/lib/components/Message.svelte
<script lang="ts">
    import Grid from "./Grid.svelte";
    import { Avatar } from "flowbite-svelte";
    import type { Message } from "$lib/messageService";

    export let message: Message | undefined = undefined;
    export let continuation: boolean = false;
    export let mb: number = 3;

    const padding = continuation ? 0.25 : mb
</script>

<div class=" {$$props.class} hover:bg-gray-200" style="padding-top: {padding*4}px; padding-bottom: {padding*2}px; padding-left: {mb*4}px">
    <Grid container alignItems="start">
        <Grid xs={0.5}>
            {#if !continuation}
                <Avatar class="h-10 w-10" src={message?.sender.avatar}/>
            {/if}
        </Grid>
        <Grid container xs={11.5} direction="col" alignItems="start">
            <Grid container>
                {#if !continuation}
                    <p><span class="font-semibold">{message?.sender.username}</span> <span
                            class="text-xs">{message?.date.toLocaleString().slice(0, -3)}</span></p>
                {/if}
            </Grid>
            <Grid>
                <p>{message?.content}</p>
            </Grid>
        </Grid>
    </Grid>
</div>
